### ISSUE TITLE
Do not use #if around IsExternalInit declaration to avoid runtime failures

### ISSUE THREAD

**Issue by AArnott** [Sholtee/primitives#1]
See [my tweet on the subject](https://twitter.com/aarnott/status/1362786409954766858) for more info.

https://github.com/Sholtee/primitives/blob/5038b28f13ada601f9b32574744d9eb21da1f322/SRC/Private/IsExternalInit.cs#L6

**Comment by Sholtee** [comment]
If i see well it won't cause any problems til i target *netstandard* only.

**Comment by Sholtee** [comment]
However in that case the #if is unnecessary

**Comment by AArnott** [comment]
Sorry, my tweet link was missing. I have corrected it in the issue description.

**Comment by Sholtee** [comment]
thx. i fixed it in [this](https://github.com/Sholtee/primitives/commit/a11cf033dffe69f2ac7615b0c88e14d90b3bebc5 ) commit
